export interface Item {
    ItemCode: string;
    ItemType: string;
    ItemCodeDesc: string;
    PriceCode: string|null;
    ProductLine: string;
    ProductType: 'F'|'R'|'K'|'D';
    StandardUnitOfMeasure: string;
    PurchaseUnitOfMeasure: string;
    SalesUnitOfMeasure: string;
    PrimaryAPDivisionNo: string;
    PrimaryVendorNo: string;
    DefaultWarehouseCode: string;
    Category1: string|null;
    Category2: string|null;
    Category3: string|null;
    Category4: string|null;
    ExplodeKitItems: string|null;
    ShipWeight: string|null;
    CommentText: string|null;
    InventoryCycle: string|null;
    RoutingNo: string|null;
    ProcurementType: string|null;
    PlannerCode: string|null;
    BuyerCode: string|null;
    PurchaseUMConvFctr: number;
    SalesUMConvFctr: number;
    SuggestedRetailPrice: string|number;
    StandardUnitPrice: string|number;
    StandardUnitCost: string|number;
    LastTotalUnitCost: string|number;
    LastAllocatedUnitCost: string|number;
    AverageUnitCost: string|number;
    Valuation: string;
    InactiveItem: 'Y'|'N';
    UDF_DUTYPCT: string|null;
    UDF_FREIGHTAIR: string|null;
    UDF_HTSCODE: string|null;
    UDF_BASEFREIGHT: string|null;
    UDF_CATALOG_DESCRIPTION: string|null;
    UDF_UPC: string|null;
    UDF_UPC_BY_COLOR: string|null;
    UDF_COUNTRY_ORIGIN: string|null;
    TotalQuantityOnHand: string|number;
}

export interface WarehouseItem {
    ItemCode:string;
    WarehouseCode: string;
    BinLocation: string|null;
    ReorderMethod: string|null;
    QuantityOnHand: string|number;
    QuantityOnPurchaseOrder: string|number;
    QuantityOnSalesOrder: string|number;
    QuantityOnBackOrder: string|number;
    AverageCost: string|number;
    QuantityRequiredForWO: string|number;
    EconomicOrderQty: string|number;
    ReorderPointQty: string|number;
    MinimumOrderQty: string|number;
    MaximumOnHandQty: string|number;
    QuantityOnWorkOrder: string|number;
    QuantityInShipping: string|number;
    TotalWarehouseValue: string|number;
    CostCalcQtyCommitted: string|number;
    CostCalcCostCommitted: string|number;
    DateCreated: string;
    TimeCreated: string;
    UserCreatedKey: string;
    DateUpdated: string;
    TimeUpdated: string;
    UserUpdatedKey: string;
}

